image: weboaks/node-karma-protractor-chrome

before_script:
  - npm install

cache:
  paths:
    - node_modules/

lint:
  script:
    - npm run lint

test:
  script:
    - npm test

build:
  script:
    - npm run build