name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Package Version Updated
        uses: MontyD/package-json-updated-action@1.0.1
        id: version-updated
        with:
          path: projects/harpokrat/package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Version
        run: echo "${{ steps.version-updated.outputs.has-updated }} ${{ steps.version-updated.outputs.current-package-version }}"
      - name: Install dependencies
        if: steps.version-updated.outputs.has-updated
        run: |
          npm config set @harpokrat:registry https://${{ secrets.NPM_REGISTRY }}/
          npm config set //${{ secrets.NPM_REGISTRY }}/:_authToken ${{ secrets.NPM_AUTH_TOKEN }}
          npm install
      - name: Build and Publish Package
        if: steps.version-updated.outputs.has-updated
        run: |
          npm run package
          cd dist/harpokrat
          npm publish --registry https://npm-registry.harpokrat.net
      - name: Create Release
        if: steps.version-updated.outputs.has-updated
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version-updated.outputs.current-package-version }}
          release_name: v${{ steps.version-updated.outputs.current-package-version }}
          draft: false
          prerelease: true
